#ifndef ERROR_H
#define ERROR_H

enum ErrorEnum {
    ERR_OK = 0,
    ERR_WRONG_ARG,
    ERR_DIMENSIONS_MISMATCH,
    ERR_DIV_BY_ZERO,
    ERR_OVERFULL,
    ERR_INVALID_STEP,
    ERR_MEMORY_ALLOCATION,
    ERR_NORM_NOT_DEFINED,
    ERR_OUT_OF_RANGE,
    ERR_VARIABLES_NUMBER_MISMATCH,
    ERR_WRONG_PROBLEM,
    ERR_OPEN_ILogImpl,
    ERR_WRITE_TO_ILogImpl,
    ERR_NOT_IMPLEMENTED,
    ERR_ANY_OTHER,

    DIMENSION_ERROR
};

#endif // ERROR_H
