#ifndef UTIL_H
#define UTIL_H

enum ErrorEnum {
    ERR_OK = 0,
    ERR_WRONG_ARG,
    ERR_DIMENSIONS_MISMATCH,
    ERR_INVALID_STEP,
    ERR_MEMORY_ALLOCATION,
    ERR_NORM_NOT_DEFINED,
    ERR_OUT_OF_RANGE,
    ERR_VARIABLES_NUMBER_MISMATCH,
    NO_SOLUTION,
};

#endif // UTIL_H

